import { slugToInterfaceName } from './naming.js';

interface FieldDefinition {
  name: string;
  type: string;
  required: boolean;
  options?: string[];
  multiple?: boolean;
  subFields?: FieldDefinition[];
  componentSlugs?: string[];
}

interface ContentTypeSchema {
  slug: string;
  name: string;
  fields: FieldDefinition[];
}

interface ComponentSchema {
  slug: string;
  name: string;
  fields: FieldDefinition[];
}

interface AuxInterface {
  name: string;
  fields: string[];
}

function fieldToTsType(
  field: FieldDefinition,
  parentName: string,
  aux: AuxInterface[],
): string {
  switch (field.type) {
    case 'text':
    case 'textarea':
    case 'email':
    case 'url':
    case 'richtext':
    case 'date':
    case 'author':
      return 'string';

    case 'number':
      return 'number';

    case 'boolean':
      return 'boolean';

    case 'select':
      if (field.options && field.options.length > 0) {
        return field.options
          .map((o) => `'${o.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`)
          .join(' | ');
      }
      return 'string';

    case 'media':
      return field.multiple ? 'string[]' : 'string';

    case 'repeatable': {
      if (!field.subFields || field.subFields.length === 0) {
        return 'unknown[]';
      }
      const itemName = `${parentName}${capitalize(field.name)}Item`;
      const itemFields = field.subFields.map((sf) => {
        const tsType = fieldToTsType(sf, itemName, aux);
        const opt = sf.required ? '' : '?';
        return `  ${sf.name}${opt}: ${tsType};`;
      });
      aux.push({ name: itemName, fields: itemFields });
      return `${itemName}[]`;
    }

    case 'component': {
      if (!field.componentSlugs || field.componentSlugs.length === 0) {
        return 'unknown[]';
      }
      const union = field.componentSlugs
        .map((s) => `${slugToInterfaceName(s)}Block`)
        .join(' | ');
      return `(${union})[]`;
    }

    default:
      return 'unknown';
  }
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function generateInterface(
  name: string,
  fields: FieldDefinition[],
  aux: AuxInterface[],
  extraFields?: string[],
): string {
  const lines = fields.map((f) => {
    const tsType = fieldToTsType(f, name, aux);
    const opt = f.required ? '' : '?';
    return `  ${f.name}${opt}: ${tsType};`;
  });
  if (extraFields) {
    lines.unshift(...extraFields);
  }
  return `export interface ${name} {\n${lines.join('\n')}\n}`;
}

export function generate(
  contentTypes: ContentTypeSchema[],
  components: ComponentSchema[],
  sourceUrl: string,
): string {
  const parts: string[] = [];
  const aux: AuxInterface[] = [];

  parts.push('// Auto-generated by @eli-cms/cli — do not edit');
  parts.push(`// Generated from: ${sourceUrl}`);
  parts.push('');

  // Component blocks
  if (components.length > 0) {
    parts.push('/** Component blocks */');
    for (const comp of components) {
      const ifaceName = `${slugToInterfaceName(comp.slug)}Block`;
      const discriminator = `  _component: '${comp.slug}';`;
      const iface = generateInterface(ifaceName, comp.fields, aux, [discriminator]);
      parts.push(iface);
      parts.push('');
    }
  }

  // Auxiliary interfaces from components (flush before content types)
  for (const a of aux) {
    parts.push(`export interface ${a.name} {\n${a.fields.join('\n')}\n}`);
    parts.push('');
  }
  aux.length = 0;

  // Content types
  if (contentTypes.length > 0) {
    parts.push('/** Content types */');
    for (const ct of contentTypes) {
      const ifaceName = slugToInterfaceName(ct.slug);
      const iface = generateInterface(ifaceName, ct.fields, aux);
      parts.push(iface);
      parts.push('');
    }
  }

  // Auxiliary interfaces from content types
  for (const a of aux) {
    parts.push(`export interface ${a.name} {\n${a.fields.join('\n')}\n}`);
    parts.push('');
  }

  // Type maps
  if (contentTypes.length > 0) {
    parts.push('/** Type maps */');
    const ctEntries = contentTypes.map(
      (ct) => `  '${ct.slug}': ${slugToInterfaceName(ct.slug)};`,
    );
    parts.push(`export interface EliContentMap {\n${ctEntries.join('\n')}\n}`);
    parts.push('');
  }

  if (components.length > 0) {
    const compEntries = components.map(
      (c) => `  '${c.slug}': ${slugToInterfaceName(c.slug)}Block;`,
    );
    parts.push(`export interface EliComponentMap {\n${compEntries.join('\n')}\n}`);
    parts.push('');
  }

  return parts.join('\n');
}
