import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generate } from '../generator.js';

describe('generate', () => {
  it('generates header with source url', () => {
    const output = generate([], [], 'http://localhost:8080');
    assert.ok(output.includes('// Auto-generated by @eli-cms/cli'));
    assert.ok(output.includes('// Generated from: http://localhost:8080'));
  });

  it('generates content type interface with basic fields', () => {
    const output = generate(
      [
        {
          slug: 'blog-post',
          name: 'Blog Post',
          fields: [
            { name: 'title', type: 'text', required: true },
            { name: 'body', type: 'richtext', required: false },
            { name: 'views', type: 'number', required: true },
            { name: 'featured', type: 'boolean', required: false },
          ],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes('export interface BlogPost {'));
    assert.ok(output.includes('  title: string;'));
    assert.ok(output.includes('  body?: string;'));
    assert.ok(output.includes('  views: number;'));
    assert.ok(output.includes('  featured?: boolean;'));
    assert.ok(output.includes("  'blog-post': BlogPost;"));
  });

  it('generates select type with options as union', () => {
    const output = generate(
      [
        {
          slug: 'article',
          name: 'Article',
          fields: [
            { name: 'category', type: 'select', required: false, options: ['tech', 'news', 'sports'] },
          ],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes("  category?: 'tech' | 'news' | 'sports';"));
  });

  it('generates select without options as string', () => {
    const output = generate(
      [
        {
          slug: 'article',
          name: 'Article',
          fields: [{ name: 'tag', type: 'select', required: false }],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes('  tag?: string;'));
  });

  it('generates media field', () => {
    const output = generate(
      [
        {
          slug: 'page',
          name: 'Page',
          fields: [
            { name: 'cover', type: 'media', required: false },
            { name: 'gallery', type: 'media', required: false, multiple: true },
          ],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes('  cover?: string;'));
    assert.ok(output.includes('  gallery?: string[];'));
  });

  it('generates repeatable field with auxiliary interface', () => {
    const output = generate(
      [
        {
          slug: 'blog-post',
          name: 'Blog Post',
          fields: [
            {
              name: 'gallery',
              type: 'repeatable',
              required: false,
              subFields: [
                { name: 'image', type: 'media', required: false },
                { name: 'caption', type: 'text', required: false },
              ],
            },
          ],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes('  gallery?: BlogPostGalleryItem[];'));
    assert.ok(output.includes('export interface BlogPostGalleryItem {'));
    assert.ok(output.includes('  image?: string;'));
    assert.ok(output.includes('  caption?: string;'));
  });

  it('generates component blocks with discriminator', () => {
    const output = generate(
      [],
      [
        {
          slug: 'hero',
          name: 'Hero',
          fields: [
            { name: 'heading', type: 'text', required: true },
            { name: 'subheading', type: 'text', required: false },
          ],
        },
      ],
      'http://localhost:8080',
    );

    assert.ok(output.includes('export interface HeroBlock {'));
    assert.ok(output.includes("  _component: 'hero';"));
    assert.ok(output.includes('  heading: string;'));
    assert.ok(output.includes('  subheading?: string;'));
    assert.ok(output.includes("  'hero': HeroBlock;"));
  });

  it('generates component field type referencing blocks', () => {
    const output = generate(
      [
        {
          slug: 'page',
          name: 'Page',
          fields: [
            {
              name: 'blocks',
              type: 'component',
              required: false,
              componentSlugs: ['hero', 'feature-grid'],
            },
          ],
        },
      ],
      [
        { slug: 'hero', name: 'Hero', fields: [] },
        { slug: 'feature-grid', name: 'Feature Grid', fields: [] },
      ],
      'http://localhost:8080',
    );

    assert.ok(output.includes('  blocks?: (HeroBlock | FeatureGridBlock)[];'));
  });

  it('generates EliContentMap and EliComponentMap', () => {
    const output = generate(
      [{ slug: 'blog-post', name: 'Blog Post', fields: [] }],
      [{ slug: 'hero', name: 'Hero', fields: [] }],
      'http://localhost:8080',
    );

    assert.ok(output.includes('export interface EliContentMap {'));
    assert.ok(output.includes("  'blog-post': BlogPost;"));
    assert.ok(output.includes('export interface EliComponentMap {'));
    assert.ok(output.includes("  'hero': HeroBlock;"));
  });

  it('handles date, email, url, author field types', () => {
    const output = generate(
      [
        {
          slug: 'event',
          name: 'Event',
          fields: [
            { name: 'startDate', type: 'date', required: true },
            { name: 'contactEmail', type: 'email', required: false },
            { name: 'website', type: 'url', required: false },
            { name: 'organizer', type: 'author', required: false },
          ],
        },
      ],
      [],
      'http://localhost:8080',
    );

    assert.ok(output.includes('  startDate: string;'));
    assert.ok(output.includes('  contactEmail?: string;'));
    assert.ok(output.includes('  website?: string;'));
    assert.ok(output.includes('  organizer?: string;'));
  });
});
